name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: dragon-build
      uses: DragonBuild/build@0.0.3
